API-Samples/07-init_uniform_buffer/07-init_uniform_buffer.cpp
Clang-format placed the matrix on a single line,
which makes the matrix hard to read.
Change-Id: If0cf58c77cea711f1c07fcf0d06a6fd6b0f1eb63
=> samples: Fix 4x4 matrix layout

Layer-Samples/Overlay/CMakeLists.txt
In the Overlay project, don't specify a build dependency
on layers in an SDK build since the layers are already built.
Also, use a consistent test to distinguish between a Repo build
and a SDK build.
Change-Id: I6d32244ee05598e56ab5e12f61f4620c12156529
=> build: Fix CMake warnings in SDK build

Sample-Programs/Hologram/Hologram.cpp
As the trace layer now supports PMB, this is no longer necessary for
a sample.
=> Hologram: Remove flush of mapped memory

API-Samples/Tutorial/markdown/01-init_instance.md
Since this is the first page of tutorials it should correctly mention that VK_SUCCESS is zero as there is no VK_ERROR_SUCCESS in the entire repo
Small type but prevent someone from doing a `if (result == VK_ERROR_SUCCESS) {}` and unable to figure out why it keeps failing check
=> Fixed VkResult const in tutorial pages

README.md
Fixes the command to invoke `update_external_sources.bat` for Windows, which doesn't work with the unix-style `./` prepended. Note: while this change allows the command to be invoked, it's failing to complete for another reason, #143.
=> fix update_external_sources command for windows

API-Samples/instance_layer_extension_properties/instance_layer_extension_properties.cpp, API-Samples/utils/util.hpp, API-Samples/utils/util_init.cpp
The sample framework currently queries the instance extensions exposed by each layer.
With this PR, device extensions are queried as well, and stored in a separate vector.
Renamed existing extension vector to "instance_extensions" for clarity.
=> samples: Query layer device extensions in init_enumerate_device

API-Samples/CMakeLists.txt, API-Samples/run_all_samples.ps1, API-Samples/validation_cache/validation_cache.cpp
This sample demonstrates the use of the VK_EXT_validation_cache
extension to persistently cache the results of SPIRV validation
when creating VkShaderModules.
=> samples: Add validation_cache

.appveyor.yml
The appveyor build got broken during the last trunk merge, since the sln file did not get changed from VULKAN.sln (which is the name in LVL) to VULKAN_SAMPLES.sln. This PR fixes that oversight.
=> build: Fix appveyor sln filename

API-Samples/utils/util.cpp
Include <string.h> for strncmp and <errno.h> for EACCES
=> android: Fix API-Samples build with NDK-r16

Sample-Programs/Hologram/Hologram.cpp, Sample-Programs/Hologram/Hologram.vert
The storage buffer used by Hologram is read-only, which is really the use case for a uniform buffer.  This, and the fact that we're getting validation errors on the vertex shader declaring the storage buffer without specifying the vertexPipelineStoresAndAtomics feature prompt a change to use a uniform buffer.
=> Samples: Hologram use uniform buffer instead of storage

CMakeLists.txt
These includes, leftover from a time before we had separate cmake files for the SDK, can cause build failures due to older headers from libvulkan-dev.  They are best removed.
=> Samples: Remove leftover SDK includes

API-Samples/utils/util.cpp, Sample-Programs/Hologram/Hologram.cpp
This update makes the API-Samples and Hologram demos compatible with the open-source version of MoltenVK, which has a slightly different extended API than the previous licensed version.
=> Update API-Samples and Hologram to be compatible with MoltenVK.

Sample-Programs/Hologram/Hologram.cpp
Hologram sample source demonstrates MoltenVK runtime config. MoltenVK runtime config has moved from VkDevice to VkInstance. This PR updates the use of MoltenVK config in the Hologram sample.
=> Hologram sample upgraded to use MoltenVK VkInstance config instead of VkDevice config.

.travis.yml, API-Samples/16-vulkan_1_1/16-vulkan_1_1.cpp, API-Samples/CMakeLists.txt, API-Samples/android/project_template/build.gradle, API-Samples/validation_cache/validation_cache.cpp, API-Samples/vulkan_1_1_flexible/vulkan_1_1_flexible.cpp
This attempts to enable the android build of Samples in Travis.  It currently takes too long and times out, so I'm looking for suggestions for shortening the build time.  Would building fewer ABIs be possible?
=> samples: Enable Android build

BUILD.md
Need to include ABI_NAME option in Android cmake command line.
=> build:Fix android cmake command

API-Samples/android/build.gradle, API-Samples/android/gradle/wrapper/gradle-wrapper.properties, API-Samples/android/project_template/build.gradle, API-Samples/android/project_template/src/main/AndroidManifest.xml
Update Gradle version and fix build files in order to get rid of all
warnings and errors when building through the latest Android Studio
3.2.0. Also remove some obsolete entries of the AndroidManifest,
which are now set by Gradle.
=> Remove all build errors on Android Studio 3.2.0

API-Samples/init_texture/init_texture.cpp
The texture file is inside asset for Android, the disk path does not work.
=> minor fix in init_texture example for Android platform

API-Samples/utils/util.cpp
Uninitialized extension fields cause parsing errors from glslang
=> Initialize Resources struct before passing to glslang

API-Samples/immutable_sampler/immutable_sampler.cpp, API-Samples/init_texture/init_texture.cpp, API-Samples/separate_image_sampler/separate_image_sampler.cpp, API-Samples/utils/util.hpp, API-Samples/utils/util_init.cpp
Changes similar to those for cube.  Cannot be guaranteed that a linear image will be available, so stage using a buffer when necessary
=> Use staging buffer instead of staging image for textures

API-Samples/push_descriptors/push_descriptors.cpp
according to fragment shader, uniform buffer and sampler
bind to different slots but VkWriteDescriptorSet sets them
to 0.
=> Samples: fix wrong bindings of push_descriptors

API-Samples/04-init_command_buffer/04-init_command_buffer.cpp
Must call init_queue_family_index before calling init_device
Change-Id: Ic2855e317487943604bd70bf1bb6e0c154a23790
=> Fix init_command_buffer order of calls

scripts/cgenerator.py, scripts/determine_vs_version.py, scripts/dispatch_table_helper_generator.py, scripts/generator.py, scripts/helper_file_generator.py, scripts/object_tracker_generator.py, scripts/parameter_validation_generator.py, scripts/reg.py, scripts/threading_generator.py, scripts/unique_objects_generator.py
This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
=> Compare to `None` using identity `is` operator

API-Samples/utils/util.cpp
When using an AMD card I was getting some validation erros from the `GLSLtoSPV` utility function. I updated the `init_resources` function to match `const TBuiltInResource DefaultTBuiltInResource` variable in the [glslang repo](https://github.com/KhronosGroup/glslang/blob/master/StandAlone/ResourceLimits.cpp).
That link should take you to the file I took the values from (**ResourceLimits.cpp**). Adding these defaults fixed the validation errors for me. Here is the error:
> Unable to parse built-ins
> ERROR: 0:3: '' :  syntax error, unexpected CONST, expecting COMMA or SEMICOLON
> INTERNAL ERROR: Unable to parse built-ins
> 
> const int  gl_MaxVertexAttribs = 64;const int  gl_MaxVertexTextureImageUnits = 32;const int  gl_MaxCombinedTextureImageUnits = 80;const int  gl_MaxTextureImageUnits = …
=> Update init_resources utility to match glslang defaults.

API-Samples/16-vulkan_1_1/16-vulkan_1_1.cpp, API-Samples/vulkan_1_1_flexible/vulkan_1_1_flexible.cpp
The 1.1 detection sample did not allow for the drivers/loader
to support > 1.1 (i.e. 1.2 or greater).
I caught this while re-evaluating our 1.1 detection logic.
=> samples: Fix 1.1 samples for future versions

scripts/lvl_genvk.py
Python 3.8 will deprecate time.clock. Replace it and also fix
the code to only calcualte times when needd.
=> build: Fix python3 warning

.appveyor.yml
This will allow us to check our build logs to determine the exact
CMake version used with that build.
=> add cmake version reporting to appveyor build

API-Samples/run_all_samples.sh
In case of image compare failure, the script attempts to set the
SAVEIMAGES variable; but it needs to be set without the initial "$"
to avoid provoking a script error:
./run_all_samples.sh: line 68: =true: command not found
Also fixed some lines with trailing spaces.
=> samples: fix error case in run_all_samples.sh script

API-Samples/utils/util.cpp, Sample-Programs/Hologram/Hologram.cpp
APISamples demo uses updated MoltenVK shader stage enumeration.
Hologram demo under MoltenVK now loads SPIR-V directly, in conformance with other platforms.
=> Updates to conversion of GLSL to SPIR-V under MoltenVK.

API-Samples/memory_barriers/memory_barriers.cpp, API-Samples/occlusion_query/occlusion_query.cpp, API-Samples/utils/util.cpp, API-Samples/utils/util.hpp, API-Samples/utils/util_init.cpp
API Samples replace use of VK_MVK_macos_surface & VK_MVK_ios_surface extensions with VK_EXT_metal_surface extension.
memory_barriers.cpp include cube_data.h using quotes
instead of angles, to align with other samples.
=> API Samples use VK_EXT_metal_surface extension

API-Samples/enable_validation_with_callback/enable_validation_with_callback.cpp, API-Samples/validation_cache/validation_cache.cpp, Sample-Programs/Hologram/Shell.cpp, Sample-Programs/Hologram/ShellWayland.cpp
VK_LAYER_LUNARG_standard_validation has been replaced by VK_LAYER_KHRONOS_validation
=> samples: Move from standard_validation to KHRONOS

API-Samples/memory_barriers/memory_barriers.cpp, API-Samples/multithreaded_command_buffers/multithreaded_command_buffers.cpp, API-Samples/utils/util_init.cpp, API-Samples/utils/util_init.hpp
Renderpass initial layout was UNDEFINED allowing pixel from previous draws to be trashed.
=> Fix renderpass to preserve image

API-Samples/run_all_samples.sh
The run_all_samples.sh script didn't check return values, leading to a potential
condition where testing via the script wouldn't detect certain types of errors.
=> tests: check return values of executed programs

API-Samples/utils/util_init.cpp
When running on different devices, the colors can appear different, because
the current code always uses the device's first reported surface format.
This change forces the use of VK_FORMAT_B8R8G8A8_UNORM if it's supported,
and falls back to using the device's first reported surface format
if that format is not supported.  This makes the generated images similar
across devices.
=> utils: use B8G8R8A8_UNORM surface format if possible

Sample-Programs/Hologram/Shell.cpp
Add a flush at the end of the log function so that the output does not gets buffered when redirected.
=> Add a flush at the end of the log function
