LunarG/VulkanSamples

- README.md
Corrected wrong directory description (src -> API-Samples) in README.md).
> Corrected wrong directory description

- Sample-Programs/Hologram/CMakeLists.txt
- Sample-Programs/Hologram/Main.cpp
- Sample-Programs/Hologram/ShellWayland.cpp
- Sample-Programs/Hologram/ShellWayland.h
Change-Id: I90a4c7cfb6e1e789eb56546545d1388c62c48439
> Hologram: Add Wayland support

- API-Samples/validation_cache/validation_cache.cpp
- CMakeLists-SDK.txt
Fixes from SDK testing feedback
> Fix assert, compile warning and loader path

- .appveyor.yml
- .gitmodules
- .travis.yml
- API-Samples/CMakeLists.txt
- API-Samples/android/project_template/build.gradle
- API-Samples/run_all_samples.ps1
- BUILD.md
- CMakeLists.txt
- README.md
- Sample-Programs/Hologram/CMakeLists.txt
- cmake/FindVulkan.cmake
- scripts/known_good.json
- scripts/update_deps.py
> Remove Vulkan-LoaderAndValidationLayers Submodule

- .travis.yml
- API-Samples/CMakeLists.txt
- CMakeLists.txt
- Sample-Programs/Hologram/CMakeLists.txt
Change-Id: I1cd883d66fd7c3fb709d9701f7f10d4a2d3489c7
> samples: Add install targets

- scripts/update_deps.py
Makes `update_deps.py` consistent between repos.
> build: Unify `update_deps.py` between repos

- API-Samples/utils/util.cpp
> Include headers to fix Windows Android build

- API-Samples/Tutorial/markdown/15-draw_cube.md
Change-Id: Ia11c8cb0b191b517bf315f32bd7f7ec3af89d6ae
> Tutorial: Fix stage to wait for swapchain image

- API-Samples/utils/util.cpp
- CMakeLists.txt
- scripts/known_good.json
Change-Id: I5f4735f3afbfc0962d211864a9c6acdf7b4e59b6
> Update known good, account for new extensions in glslang

- CMakeLists-SDK.txt
Same as previous change, but for the SDK CMake
> Account for new extensions in glslang

- scripts/known_good.json
Change-Id: If314bef44ad2dc142e4dd38a208e87b74ec07854
> Update known-good for 1.1.90 headers

- API-Samples/android/vulkan_wrapper/vulkan_wrapper.cpp
- API-Samples/android/vulkan_wrapper/vulkan_wrapper.h
- scripts/known_good.json
Includes updated vulkan_wrapper.[cpp,h]
> repo: Update known-good for 1.1.91 headers

- scripts/known_good.json
Change-Id: I35c82719a6eb02eeaa826fad3cec90b5452313c3
> Update known good for 1.1.97 headers

- API-Samples/05-init_swapchain/05-init_swapchain.cpp
- API-Samples/07-init_uniform_buffer/07-init_uniform_buffer.cpp
- API-Samples/10-init_render_pass/10-init_render_pass.cpp
- API-Samples/12-init_frame_buffers/12-init_frame_buffers.cpp
Driver may fail to create swapchain otherwise
Change-Id: I266b82cd02d00dad0f4282bde255d1bf13593583
> Use 64x64 extent for test windows

- samples_index.html
De-emphasized LunarG and Valve. Put in the Vulkan logo
> SDK branding changes

- .appveyor.yml
- .travis.yml
This is helpful for identifying when Travis changes its cmake version
> Bob travis cmake version

- BUILD.md
Change-Id: Icdc90e0ac7bcf43ca702d6b0353d036dd4d9ccc5
> docs: Update BUILD.md for CMake versions

- scripts/known_good.json
Change-Id: If821f84d7419bc52838377bf67f0214ffa0b46a4
> Update known good for 1.1.106 header

- .appveyor.yml
- BUILD.md
- build_windows_samples_sdk.bat
Stay in sync with other Vulkan repos
> build: Move minimum MSVC version to 2015

- build_windows_samples_sdk.bat
- build_windows_targets.bat
> Specify UTF-8 for character encoding

- API-Samples/utils/util_init.cpp
Change-Id: I55c1dab95a67ed07edb1ed9ec28f5b9355ba2c53
> Fix loop counter in utils

- BUILD.md
[skip-ci]
Analogue of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/955
> docs: Improve instructions for using update_deps

- API-Samples/CMakeLists.txt
- BUILD.md
- CMakeLists-SDK.txt
- CMakeLists.txt
- Layer-Samples/Overlay/CMakeLists.txt
- Sample-Programs/Hologram/android/CMakeLists.txt
Also, cmake_minimum_required() must occur before the project() command,
see https://cmake.org/cmake/help/latest/command/project.html
Change-Id: I46f1b1a7ca40df2c0d1973666f06dd22bfb707b3
> build: Update cmake_minimum_required(VERSION 3.10.2)

- scripts/known_good.json
Also update glslang version
Change-Id: I4a76c820192c78b9fe407bd13e41dedb00b973a8
> build: Update known good for 1.1.114 header

- API-Samples/utils/util_init.cpp
> samples: Better depth format selection on Android

- BUILD.md
armabi-v7a should be armeabi-v7a
> Fix typo in BUILD.md for Android

- API-Samples/10-init_render_pass/10-init_render_pass.cpp
- API-Samples/Tutorial/markdown/10-init_render_pass.md
- API-Samples/draw_subpasses/draw_subpasses.cpp
- API-Samples/input_attachment/input_attachment.cpp
- API-Samples/utils/util_init.cpp
- Sample-Programs/Hologram/Hologram.cpp
> Add swapchain image dependency at COLOR_ATTACHMENT_OUTPUT

- scripts/known_good.json
Change-Id: I4faddf4864ec90da143ba42b6add79f38d58ed51
> Update to 1.1.130 headers

- API-Samples/Tutorial/markdown/00-intro.md
vulkan.h is no longer part of the samples repository.  Addresses #275
> Fix location of vulkan.h in the tutorial

- scripts/known_good.json
Change-Id: I60a8eaa5c078ff78b1c66fc0e6164204770711e4
> Update to 1.2.131 headers

- API-Samples/utils/util_init.cpp
> Be sure Load Op and layouts make sense

- .travis.yml
Change-Id: I3865b0b4a4c05f3eca3c5b75b44eb847fa21d3e4
> Fix travis android build

- API-Samples/run_all_samples.py
We want it to work on more than just Windows.  Follows the algorithm used in the .sh file to collect all of the sample names
> Fix python script for non-Windows OS

- API-Samples/android/compile_shaders.py
- BUILD.md
add Windows, Mac OS  support to compile_shader.py, this fix issue #288. Please take a look, thank you!
> fix issue 288

- API-Samples/14-init_pipeline/14-init_pipeline.cpp
- API-Samples/Tutorial/markdown/14-init_pipeline.md
- API-Samples/draw_subpasses/draw_subpasses.cpp
- API-Samples/pipeline_derivative/pipeline_derivative.cpp
- API-Samples/utils/util_init.cpp
Change-Id: If1589ff8d179ada9eb944c5864bedd71d924cdd3
> Remove dependency on VK_DYNAMIC_STATE_RANGE_SIZE

- scripts/known_good.json
Change-Id: Ic8c0a94c1655c94de574d15cdd1843735c3a2edd
> Update to 1.2.154 headers
